### ISSUE TITLE
Invalid input data running an ASPIF input

### ISSUE THREAD

**Issue by David-Tuc** [MatthiasNickles/diff-SAT#2]
Dear Matthias,
I have been trying to run the diff-SAT for the probabilistic part of it (PrASP), but can't get the system to accept the aspif file. It is probably something I am doing wrong myself. I have been trying so far using your examples in the readme. 

I have tested the 0.5.0 and 0.5.2 releases, getting the same behavior.

1. Create file test.lp and copy paste in it the code in example (1).
2. Run "clingo test.lp --trans-ext=all --pre=aspif > test.aspif"
3. Run "java -jar diffSAT.jar test.aspif -n 100 --solverarg diversify true --solverarg suppressAnswers true --solverarg showProbsOfSymbols true"
4. Stdout: "diff-SAT 0.5.2

Error [-100]: Invalid input data:"

Desktop:
 - OS: tested on Windows and Linux

Best Wishes
David

 ---------------------------------------------------------------
Here I am copy-pasting the content of test.aspif:
asp 1 0 0
1 0 1 1 0 0
1 0 1 2 0 0
1 0 1 3 0 0
1 0 1 4 0 0
1 0 1 8 0 0
1 0 1 9 0 0
1 0 0 0 1 -11
1 0 1 13 0 1 11
1 0 0 0 1 -15
1 0 1 17 0 1 15
1 0 1 5 0 2 6 7
1 0 0 0 2 10 7
1 0 0 0 2 14 6
1 0 1 10 0 1 -18
1 0 1 11 0 1 -18
1 0 1 18 0 1 -10
1 0 1 7 0 1 -19
1 0 1 11 0 1 -19
1 0 1 19 0 1 -7
1 0 1 14 0 1 -20
1 0 1 15 0 1 -20
1 0 1 20 0 1 -14
1 0 1 6 0 1 -21
1 0 1 15 0 1 -21
1 0 1 21 0 1 -6
4 7 coin(1) 0
4 7 coin(2) 0
4 19 _pr_(heads(1),5000) 0
4 19 _pr_(heads(2),5000) 0
4 3 win 1 5
4 8 heads(2) 1 6
4 8 heads(1) 1 7
4 8 tails(1) 1 10
4 8 tails(2) 1 14
0

**Comment by MatthiasNickles** [comment]
Dear David,
 
thanks for reporting this behavior. It looks like an encoding issue: the aspif file generated
by clingo appears to be in UCS-2 format (which adds unrecognized extra bytes to the
file header), whereas the current version of diff-SAT expects input in UTF-8.
 
A quick workaround is to open the generated aspif file with Notepad++ (or some other editor which 
supports switching between encodings), to change the encoding there to UTF-8, and to save the file.
 
Best regards,
 
Matthias

**Comment by David-Tuc** [comment]
Dear Matthias, 

Indeed that does the trick ! Thank you very much. 

Best Wishes
David

**Comment by MatthiasNickles** [comment]
Addendum: The next version of diff-SAT (planned to appear in ca. 1-2 weeks) will support input files in UCS-2 and UTF-16 encoding directly.
